// <auto-generated />
using System;
using Logistics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logistics.Infrastructure.Migrations.InitialCreate
{
    [DbContext(typeof(LogisticsDbContext))]
    partial class LogisticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logistics.Infrastructure.Persistence.BookingEntity", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid?>("ActiveHoldId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_hold_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("RequestedCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("requested_capacity");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("VoyageId")
                        .HasColumnType("uuid")
                        .HasColumnName("voyage_id");

                    b.HasKey("BookingId");

                    b.HasIndex("VoyageId");

                    b.ToTable("booking", (string)null);
                });

            modelBuilder.Entity("Logistics.Infrastructure.Persistence.CapacityHoldEntity", b =>
                {
                    b.Property<Guid>("HoldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("hold_id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<int>("CapacityUnits")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_units");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("VoyageId")
                        .HasColumnType("uuid")
                        .HasColumnName("voyage_id");

                    b.HasKey("HoldId");

                    b.HasIndex("VoyageId");

                    b.HasIndex("BookingId", "Status")
                        .HasDatabaseName("ix_capacity_hold_booking_status");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_capacity_hold_status_expiresat");

                    b.ToTable("capacity_hold", (string)null);
                });

            modelBuilder.Entity("Logistics.Infrastructure.Persistence.IdempotencyEntryEntity", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RequestHash")
                        .HasColumnType("text")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text")
                        .HasColumnName("result_json");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("IdempotencyKey");

                    b.ToTable("idempotency_entry", (string)null);
                });

            modelBuilder.Entity("Logistics.Infrastructure.Persistence.InboxEntryEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("MessageId");

                    b.ToTable("inbox_entry", (string)null);
                });

            modelBuilder.Entity("Logistics.Infrastructure.Persistence.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("processed");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("Id");

                    b.HasIndex("Processed", "OccurredAt")
                        .HasDatabaseName("ix_outbox_processed_occurredat");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("Logistics.Infrastructure.Persistence.VoyageCapacityEntity", b =>
                {
                    b.Property<Guid>("VoyageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("voyage_id");

                    b.Property<int>("ConfirmedCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("confirmed_capacity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("HeldCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("held_capacity");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operational_status");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("total_capacity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("VoyageId");

                    b.ToTable("voyage_capacity", null, t =>
                        {
                            t.HasCheckConstraint("ck_voyage_capacity_sum", "(held_capacity + confirmed_capacity) <= total_capacity");

                            t.HasCheckConstraint("ck_voyage_non_negative", "total_capacity >= 0 AND held_capacity >= 0 AND confirmed_capacity >= 0");
                        });
                });

            modelBuilder.Entity("Logistics.Infrastructure.Persistence.BookingEntity", b =>
                {
                    b.HasOne("Logistics.Infrastructure.Persistence.VoyageCapacityEntity", null)
                        .WithMany()
                        .HasForeignKey("VoyageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_voyage");
                });

            modelBuilder.Entity("Logistics.Infrastructure.Persistence.CapacityHoldEntity", b =>
                {
                    b.HasOne("Logistics.Infrastructure.Persistence.BookingEntity", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_capacityhold_booking");

                    b.HasOne("Logistics.Infrastructure.Persistence.VoyageCapacityEntity", null)
                        .WithMany()
                        .HasForeignKey("VoyageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_capacityhold_voyage");
                });
#pragma warning restore 612, 618
        }
    }
}
